"$schema" = 'https://starship.rs/config-schema.json'

# Activate Palette
palette = 'warthunder'

[palettes.warthunder]
background = '#282828'
foreground = '#3c3836'
orange = '#fead6a'
grey_text = '#ebdbb2'
grey_dim = '#928374'
red = '#cc241d'
green = '#98971a'


# Main Prompt Format
format = """
$username$ssh$directory$line_break$character $cmd_duration"""

# --- Modules ---

[username]
show_always = true
style_user = "bold yellow"
style_root = "bold red"
format = '[$user]($style)'

[hostname]
disabled = false
ssh_only = false
style = "bold yellow"
format = '[@$hostname]($style) '   
ssh_symbol = "[-󰣀 ] "

[directory]
style = "bright-blue"
format = '[$path]($style)$read_only '
truncation_length = 0
read_only = " "
read_only_style = "red bold"   
[line_break]
disabled = false

[character]
success_symbol = '[└─➤](yellow)'
error_symbol = '[└─➤](yellow)'

[cmd_duration]
disabled = false
show_milliseconds = false
show_notifications = false
min_time_to_notify = 45000
format = " [󰔛️ $duration ](bold pink)"
