palette = "dracula"

# Define Dracula color palette
[palettes.dracula]
background = "#282a36"
current_line = "#44475a"
foreground = "#f8f8f2"
comment = "#6272a4"
cyan = "#8be9fd"
green = "#50fa7b"
orange = "#ffb86c"
pink = "#ff79c6"
purple = "#bd93f9"
red = "#ff5555"
yellow = "#f1fa8c"

## FIRST LINE/ROW: Info & Status
[username]
format = "[❮]($style)[$user]($style)[@]($style)"
show_always = true
style_root = "bold red"
style_user = "bold orange"

[hostname]
disabled = false
format = "[$hostname]($style)[$ssh_symbol]($style)[❯]($style) "
ssh_only = false
style = "bold orange"
ssh_symbol = "󰌀 "

[directory]
style = "cyan"
truncate_to_repo = false
truncation_length = 0
format = "[➤ ](bold orange)[❮]($style)[$path]($style)[❯]($style)"
read_only = " "


[sudo]
disabled = true

[cmd_duration]
disabled = false
style="bold pink"
format = " took [$duration]($style)"
show_milliseconds = false
show_notifications = false
min_time_to_notify = 30_000

[os]
disabled = false
format = '[└]($style)[$symbol]($style)'
style = "bold green"

[character]
error_symbol = ""
success_symbol = "[ ➤](bold green)"

# SYMBOLS
[os.symbols]
Alpine = " "
AlmaLinux = " "
Android = " "
Arch = " "
CentOS = " "
Debian = " "
EndeavourOS = " "
Fedora = " "
Garuda = "󰛓 "
Linux = " "
Macos = " "
Manjaro = " "
Mint = "󰣭"
openSUSE = " "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "
