font_family    JetBrainsMono Nerd Font
font_size 10
scrollback_lines 2000
wheel_scroll_min_lines 1
initial_window_width  20c
initial_window_height 10c
window_padding_width 5
enable_audio_bell yes
is_kitty_gui_cmdline true
allow_remote_control yes
watcher

listen_on unix:/tmp/kitty_remote.sock

tab_bar_edge bottom
tab_bar_margin_width 0.0
tab_bar_margin_height 0.0 0.0
tab_bar_style powerline
tab_bar_align left
ab_powerline_style slanted
tab_activity_symbol 
# active_tab_background   #eee
active_tab_font_style   bold-italic
inactive_tab_font_style normal


editor micro 
allow_hyperlinks yes
confirm_os_window_close 0
kitty_mod ctrl+shift
map ctrl+tab        next_tab
map ctrl+shift+tab previous_tab
map ctrl+t       new_tab
map kitty_mod+q close_tab
map ctrl+f5 load_config_file

#include ~/.cache/wal/colors-kitty.conf

# BEGIN_KITTY_THEME
background_opacity 0.8
# Gruvbox Dark Hard
#include current-theme.conf
include Tango_Dark.conf
# END_KITTY_THEME
